bazel_dep(name = "aspect_bazel_lib", version = "2.21.1")
bazel_dep(name = "aspect_rules_lint", version = "1.7.0")
bazel_dep(name = "aspect_rules_py", version = "1.6.5")
bazel_dep(name = "bazel_env.bzl", version = "0.5.0")
bazel_dep(name = "bazelrc-preset.bzl", version = "1.2.0")
bazel_dep(name = "buildifier_prebuilt", version = "8.2.0.2")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_multitool", version = "1.9.0")
bazel_dep(name = "rules_python", version = "1.6.1")
bazel_dep(name = "rules_python_gazelle_plugin", version = "1.6.1")
bazel_dep(name = "rules_shell", version = "0.6.0")
bazel_dep(name = "rules_uv", version = "0.88.0")
bazel_dep(name = "tar.bzl", version = "0.5.5")

multitool = use_extension("@rules_multitool//multitool:extension.bzl", "multitool")
multitool.hub(lockfile = "//tools:tools.lock.json")
use_repo(multitool, "multitool")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.12",
)
